### ISSUE TITLE
Error starting (Minetest 5.1)

### ISSUE THREAD

**Issue by KingBBQ** [TalkLounge/plot_system#3]
When starting a new world wich the mod enabled, i get this errer:

2021-03-28 13:00:58: ERROR[Main]: ModError: Failed to load and run script from /home/kingbbq/.minetest/mods/plot_system/init.lua:
2021-03-28 13:00:58: ERROR[Main]: /home/kingbbq/.minetest/mods/plot_system/init.lua:214: attempt to concatenate a table value
2021-03-28 13:00:58: ERROR[Main]: stack traceback:
2021-03-28 13:00:58: ERROR[Main]: 	/home/kingbbq/.minetest/mods/plot_system/init.lua:214: in main chunk
2021-03-28 13:00:58: ERROR[Main]: Für mehr Details siehe debug.txt.
2021-03-28 13:00:58: ACTION[Main]: Server: Shutting down

**Comment by TalkLounge** [comment]
Has been fixed
Thanks for reporting

**Comment by KingBBQ** [comment]
thanks for the quick reply.

I still get the same error, see attached screenshot. 

cheers
Gregor




Am Sonntag, dem 28.03.2021 um 05:13 -0700 schrieb TalkLounge:
> Has been fixed
> Thanks for reporting
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Hello and good evenening from Augsburg, Germany :-)

I work a lot with kids in Minecraft - especially with ComputerCraft and
ComputercraftEDU: I created a modpack with these mods, special worlds
and more, for kids to learn how to code within Minecraft. Where else
would you like to start coding?

Right now its a ZIP they can install directly:
https://handbuch.kidslab.de/minecraft/allgemeines/modpacks
(attention, German!)

KidsLab.de is a non profit organisation, showing kids the creative 
sides of computers and gaming.

cheers
Gregor

**Comment by TalkLounge** [comment]
There is no screenshot...

Have you downloaded the mod again?
